// GENERATED by scripts/build-docs.mjs — do not hand-edit.
// The manifest the sidebar, search and generated home page read at runtime on
// every page (plain ES module, no build step for the browser).
export const CATEGORIES = [
  {
    "name": "Actions",
    "slugs": [
      "speed-dial",
      "split-button",
      "toggle-group",
      "wizard",
      "button-group",
      "icon-button",
      "toggle",
      "toolbar",
      "kbd",
      "button"
    ]
  },
  {
    "name": "Forms",
    "slugs": [
      "autocomplete",
      "calendar",
      "color-picker",
      "combobox",
      "date-picker",
      "date-range-picker",
      "date-time-picker",
      "file-upload",
      "multi-select",
      "number-field",
      "radio-group",
      "rating",
      "tags-input",
      "time-picker",
      "label",
      "form",
      "field-array",
      "input-otp",
      "phone-input",
      "editable",
      "input",
      "textarea",
      "field",
      "select",
      "checkbox",
      "checkbox-group",
      "switch",
      "slider",
      "input-group"
    ]
  },
  {
    "name": "Data display",
    "slugs": [
      "code-block",
      "data-table",
      "tree",
      "item",
      "marker",
      "snippet",
      "qr-code",
      "meter",
      "relative-time",
      "chart",
      "line-chart",
      "area-chart",
      "bar-chart",
      "stacked-bar",
      "pie-chart",
      "donut-chart",
      "gauge",
      "sparkline",
      "radar-chart",
      "combo-chart",
      "funnel-chart",
      "scatter-chart",
      "treemap",
      "waterfall-chart",
      "heatmap",
      "bullet-chart",
      "timeline",
      "avatar",
      "agenda",
      "table",
      "empty",
      "progress",
      "description-list",
      "spinner",
      "card",
      "badge",
      "status",
      "tag",
      "kanban",
      "skeleton"
    ]
  },
  {
    "name": "Navigation",
    "slugs": [
      "command",
      "menubar",
      "navigation-menu",
      "sidebar",
      "tabs",
      "toc",
      "stepper",
      "pagination",
      "breadcrumb"
    ]
  },
  {
    "name": "Layout",
    "slugs": [
      "aspect-ratio",
      "separator",
      "scroll-area",
      "resizable",
      "masonry",
      "theme-switcher",
      "carousel",
      "wordmark",
      "banner",
      "page-header",
      "panel"
    ]
  },
  {
    "name": "Disclosure",
    "slugs": [
      "accordion",
      "collapsible"
    ]
  },
  {
    "name": "Overlays",
    "slugs": [
      "alert-dialog",
      "context-menu",
      "dialog",
      "dropdown-menu",
      "hover-card",
      "popover",
      "sheet",
      "drawer",
      "tooltip"
    ]
  },
  {
    "name": "Feedback",
    "slugs": [
      "alert",
      "toast"
    ]
  },
  {
    "name": "Conversation",
    "slugs": [
      "bubble",
      "message",
      "message-scroller",
      "attachment"
    ]
  },
  {
    "name": "Utilities",
    "slugs": [
      "direction",
      "icon"
    ]
  }
]

export const COMPONENTS = {
  "speed-dial": {
    "name": "Speed Dial",
    "description": "A floating action button whose two-to-four actions fan out on open — the create button a whole view is about.",
    "category": "Actions",
    "exampleCount": 3,
    "legacy": null
  },
  "split-button": {
    "name": "SplitButton",
    "description": "One primary action, with its variants behind an attached caret.",
    "category": "Actions",
    "exampleCount": 1,
    "legacy": "button-extras"
  },
  "toggle-group": {
    "name": "Segmented",
    "description": "A short row of mutually exclusive options, all visible at once.",
    "category": "Actions",
    "exampleCount": 1,
    "legacy": "segmented"
  },
  "wizard": {
    "name": "Wizard",
    "description": "An ordered sequence of steps, with the progress and the navigation handled.",
    "category": "Actions",
    "exampleCount": 1,
    "legacy": "wizard"
  },
  "button-group": {
    "name": "Button Group",
    "description": "Joins related buttons into a single segmented control with shared borders.",
    "category": "Actions",
    "exampleCount": 4,
    "legacy": "button-extras"
  },
  "icon-button": {
    "name": "Icon Button",
    "description": "`Button` for an icon alone, with an accessible name it cannot ship without.",
    "category": "Actions",
    "exampleCount": 3,
    "legacy": "buttons"
  },
  "toggle": {
    "name": "Toggle",
    "description": "A two-state button for on/off formatting controls.",
    "category": "Actions",
    "exampleCount": 4,
    "legacy": "toggle"
  },
  "autocomplete": {
    "name": "Autocomplete",
    "description": "Free-text input with suggestions — unlike Combobox, the typed value need not come from the list.",
    "category": "Forms",
    "exampleCount": 4,
    "legacy": "combobox"
  },
  "calendar": {
    "name": "Calendar",
    "description": "A month grid with dated events, statuses and a selected day.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "calendar-view"
  },
  "color-picker": {
    "name": "ColorPicker",
    "description": "A swatch group over the brand palette, with a free-form hex field beside it.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "color-picker"
  },
  "combobox": {
    "name": "Combobox",
    "description": "A text field that filters a list as you type, and settles on one value.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "combobox"
  },
  "date-picker": {
    "name": "DatePicker",
    "description": "One date, from a field with a calendar under it.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "date-picker"
  },
  "date-range-picker": {
    "name": "DateRangePicker",
    "description": "A start and an end, picked together in one calendar.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "date-range"
  },
  "date-time-picker": {
    "name": "DateTimePicker",
    "description": "A date and a time in one field, on the native `datetime-local` control.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "date-time"
  },
  "file-upload": {
    "name": "FileUpload",
    "description": "A drop zone that is also a file button, with the picked files listed under it.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "file-upload"
  },
  "multi-select": {
    "name": "MultiSelect",
    "description": "Several values from a fixed list, shown as removable chips.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "multi-select"
  },
  "number-field": {
    "name": "NumberInput",
    "description": "A numeric field with stepper buttons and a real `null` for empty.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "number-input"
  },
  "radio-group": {
    "name": "RadioGroup",
    "description": "One choice from a few, over native `<input type=\"radio\">`.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "form-controls"
  },
  "rating": {
    "name": "Rating",
    "description": "A star scale, as an input or as a read-only display.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "rating"
  },
  "tags-input": {
    "name": "TagInput",
    "description": "Free-form labels, entered one at a time and shown as removable chips.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "tag-input"
  },
  "time-picker": {
    "name": "TimePicker",
    "description": "A time of day, in 24-hour `HH:mm`.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": "time-picker"
  },
  "label": {
    "name": "Label",
    "description": "An accessible label; pairs with a control via `htmlFor` and dims with its disabled state.",
    "category": "Forms",
    "exampleCount": 4,
    "legacy": "forms"
  },
  "form": {
    "name": "Form",
    "description": "A thin Base UI Form wrapper: the page-level `<form>` and its vertical rhythm. `FormField` owns everything inside it.",
    "category": "Forms",
    "exampleCount": 4,
    "legacy": "forms"
  },
  "field-array": {
    "name": "Field Array",
    "description": "Repeated entries for an array of objects — one bordered block per entry, each removable, with one add button under the stack.",
    "category": "Forms",
    "exampleCount": 3,
    "legacy": "forms"
  },
  "input-otp": {
    "name": "Input OTP",
    "description": "A segmented one-time-code field with per-character slots. Stylesheet only — the one-field-many-boxes behaviour needs a binding this package does not ship.",
    "category": "Forms",
    "exampleCount": 1,
    "legacy": null
  },
  "phone-input": {
    "name": "Phone Input",
    "description": "A country dial-code select paired with a national-number field, composing into one E.164-ish string value.",
    "category": "Forms",
    "exampleCount": 3,
    "legacy": null
  },
  "editable": {
    "name": "Editable",
    "description": "Inline click-to-edit text — a preview with an edit affordance that swaps to a field, committed on Enter or blur, discarded on Escape.",
    "category": "Forms",
    "exampleCount": 4,
    "legacy": null
  },
  "code-block": {
    "name": "CodeBlock",
    "description": "A source snippet with a filename strip and a copy button.",
    "category": "Data display",
    "exampleCount": 1,
    "legacy": "code-block"
  },
  "data-table": {
    "name": "DataGrid",
    "description": "A real `<table>` with sorting, selection, filtering, inline edit and paging.",
    "category": "Data display",
    "exampleCount": 2,
    "legacy": "datagrid"
  },
  "tree": {
    "name": "Tree",
    "description": "A nested, expandable hierarchy — files, org units, categories.",
    "category": "Data display",
    "exampleCount": 1,
    "legacy": "tree"
  },
  "item": {
    "name": "Item",
    "description": "A list row with media, content and actions slots — lighter than a Card for repeated rows.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": null
  },
  "marker": {
    "name": "Marker",
    "description": "A small inline badge pairing an icon with a label.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": null
  },
  "snippet": {
    "name": "Snippet",
    "description": "A one-line copyable command. Shares Code Block's copy affordance rather than restating it.",
    "category": "Data display",
    "exampleCount": 2,
    "legacy": "code-block"
  },
  "qr-code": {
    "name": "QR Code",
    "description": "Renders a QR code as inline SVG from a hand-rolled byte-mode encoder — no dependency, no network, no canvas. Versions 1-10, all four correction levels.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": null
  },
  "meter": {
    "name": "Meter",
    "description": "Displays a measured value within a known range — capacity, not task progress.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "form-controls"
  },
  "relative-time": {
    "name": "Relative Time",
    "description": "Renders \"3 hours ago\" from a date, inside a `time` element that keeps the machine-readable timestamp.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": null
  },
  "command": {
    "name": "CommandPalette",
    "description": "The ⌘K surface: one flat list of commands, grouped and filtered as you type.",
    "category": "Navigation",
    "exampleCount": 1,
    "legacy": "command-palette"
  },
  "menubar": {
    "name": "Menubar",
    "description": "A desktop-style application menu bar with keyboard traversal.",
    "category": "Navigation",
    "exampleCount": 4,
    "legacy": "menu"
  },
  "navigation-menu": {
    "name": "Navigation Menu",
    "description": "A horizontal site menu with optional rich dropdown panels.",
    "category": "Navigation",
    "exampleCount": 4,
    "legacy": null
  },
  "sidebar": {
    "name": "VerticalNav",
    "description": "The app's own nav column: one level of nesting, one active row.",
    "category": "Navigation",
    "exampleCount": 1,
    "legacy": "vertical-nav"
  },
  "tabs": {
    "name": "Tabs",
    "description": "Sibling views of one subject, one visible at a time.",
    "category": "Navigation",
    "exampleCount": 1,
    "legacy": "tabs"
  },
  "toc": {
    "name": "Toc",
    "description": "The in-page anchor rail — a sticky list of the sections on the current page.",
    "category": "Navigation",
    "exampleCount": 4,
    "legacy": null
  },
  "aspect-ratio": {
    "name": "Aspect Ratio",
    "description": "Constrains content to a fixed width-to-height ratio.",
    "category": "Layout",
    "exampleCount": 4,
    "legacy": null
  },
  "separator": {
    "name": "Separator",
    "description": "A rule between content. Base UI inverts the orientation semantics — a horizontal group takes vertical separators.",
    "category": "Layout",
    "exampleCount": 4,
    "legacy": "dividers"
  },
  "scroll-area": {
    "name": "Scroll Area",
    "description": "A scrollable region with styled, overlay scrollbars.",
    "category": "Layout",
    "exampleCount": 3,
    "legacy": null
  },
  "resizable": {
    "name": "Resizable",
    "description": "Panel groups split by draggable handles. Stylesheet only — the drag needs a binding this package does not ship.",
    "category": "Layout",
    "exampleCount": 1,
    "legacy": null
  },
  "masonry": {
    "name": "Masonry",
    "description": "A multi-column layout that balances items of uneven height, via CSS columns rather than a JS measurement pass.",
    "category": "Layout",
    "exampleCount": 3,
    "legacy": null
  },
  "theme-switcher": {
    "name": "Theme Switcher",
    "description": "A light/dark/system toggle, promoted from the docs app's own theme-toggle. Fully controlled — the consumer owns the theme hook.",
    "category": "Layout",
    "exampleCount": 5,
    "legacy": null
  },
  "carousel": {
    "name": "Carousel",
    "description": "A paged slide viewport with previous and next controls. Stylesheet only — the drag and snap need a binding this package does not ship.",
    "category": "Layout",
    "exampleCount": 1,
    "legacy": null
  },
  "wordmark": {
    "name": "Wordmark",
    "description": "The Diametral logo lockup, inlined as JSX so it recolours with the surrounding text.",
    "category": "Layout",
    "exampleCount": 3,
    "legacy": null
  },
  "accordion": {
    "name": "Accordion",
    "description": "A stack of disclosure rows, driven by an `items` array rather than composed from children.",
    "category": "Disclosure",
    "exampleCount": 1,
    "legacy": "accordion"
  },
  "collapsible": {
    "name": "Collapsible",
    "description": "A single show/hide region. Emits `data-open` / `data-closed`, not `data-state`.",
    "category": "Disclosure",
    "exampleCount": 4,
    "legacy": "accordion"
  },
  "alert-dialog": {
    "name": "Modal",
    "description": "The destructive-confirmation shape of `Modal`: a heading, the consequence, and two buttons.",
    "category": "Overlays",
    "exampleCount": 1,
    "legacy": "modal"
  },
  "context-menu": {
    "name": "ContextMenu",
    "description": "Right-click's own menu, positioned at the pointer.",
    "category": "Overlays",
    "exampleCount": 4,
    "legacy": "menu"
  },
  "dialog": {
    "name": "Modal",
    "description": "A focused task on top of the page: heading, body, footer actions.",
    "category": "Overlays",
    "exampleCount": 1,
    "legacy": "modal"
  },
  "dropdown-menu": {
    "name": "Dropdown",
    "description": "A menu of actions hanging off a trigger.",
    "category": "Overlays",
    "exampleCount": 1,
    "legacy": "menu"
  },
  "hover-card": {
    "name": "Hover Card",
    "description": "A preview surface shown on hover, for links and mentions.",
    "category": "Overlays",
    "exampleCount": 3,
    "legacy": "popover"
  },
  "popover": {
    "name": "Popover",
    "description": "A small panel anchored to a trigger, for detail that would crowd the page.",
    "category": "Overlays",
    "exampleCount": 1,
    "legacy": "popover"
  },
  "alert": {
    "name": "Alert",
    "description": "An inline message about the thing next to it. Four types, optionally dismissible.",
    "category": "Feedback",
    "exampleCount": 1,
    "legacy": "alert"
  },
  "toast": {
    "name": "Toast",
    "description": "A transient confirmation that an action landed, raised from anywhere via `useToast`.",
    "category": "Feedback",
    "exampleCount": 1,
    "legacy": "toast"
  },
  "bubble": {
    "name": "Bubble",
    "description": "Chat bubbles grouped by author.",
    "category": "Conversation",
    "exampleCount": 4,
    "legacy": null
  },
  "message": {
    "name": "Message",
    "description": "A conversation row with avatar and content.",
    "category": "Conversation",
    "exampleCount": 4,
    "legacy": null
  },
  "message-scroller": {
    "name": "Message Scroller",
    "description": "A transcript viewport that keeps itself pinned to the latest message. Stylesheet only — the pinning needs a binding this package does not ship.",
    "category": "Conversation",
    "exampleCount": 1,
    "legacy": null
  },
  "attachment": {
    "name": "Attachment",
    "description": "File metadata display for a message. Not an upload input — see File Upload.",
    "category": "Conversation",
    "exampleCount": 4,
    "legacy": "file-upload"
  },
  "direction": {
    "name": "Direction",
    "description": "A provider that sets text direction (LTR/RTL) for every Base UI component beneath it.",
    "category": "Utilities",
    "exampleCount": 3,
    "legacy": null
  },
  "chart": {
    "name": "Chart",
    "description": "Recharts wrapped so series colours come from a `ChartConfig` and resolve to brand chart tokens.",
    "category": "Data display",
    "exampleCount": 2,
    "legacy": "charts"
  },
  "line-chart": {
    "name": "Line Chart",
    "description": "A finished line chart over the Chart primitives — grid, axis, tooltip and legend already wired to one `config`.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": null
  },
  "area-chart": {
    "name": "Area Chart",
    "description": "`Line Chart` read as a volume — the same props, with a filled band under each series.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "charts"
  },
  "bar-chart": {
    "name": "Bar Chart",
    "description": "Categorical bars with a pinned value axis, a row layout, and per-bar semantic tinting.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "charts"
  },
  "stacked-bar": {
    "name": "Stacked Bar",
    "description": "Proportional bars — every row normalised to its own total, so only the split differs.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "charts"
  },
  "pie-chart": {
    "name": "Pie Chart",
    "description": "A whole split into slices, coloured per slice from a `config` keyed by slice name.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "charts"
  },
  "donut-chart": {
    "name": "Donut Chart",
    "description": "`Pie Chart` with the middle cut out, and a figure in the hole.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "charts"
  },
  "gauge": {
    "name": "Gauge",
    "description": "A radial progress dial for a bounded value, with optional thresholds that recolour the arc.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "charts"
  },
  "sparkline": {
    "name": "Sparkline",
    "description": "An inline mini line chart, small and cheap enough to sit in every row of a table.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "sparkline"
  },
  "radar-chart": {
    "name": "Radar Chart",
    "description": "A spider chart — how two or three entities compare across many dimensions at once.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "charts"
  },
  "combo-chart": {
    "name": "Combo Chart",
    "description": "Bars and a line on one x axis, with a second Y scale — the volume-plus-rate dashboard shape.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "charts"
  },
  "funnel-chart": {
    "name": "Funnel Chart",
    "description": "Ordered conversion stages with the drop-off derived for you from raw counts.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "charts"
  },
  "scatter-chart": {
    "name": "Scatter Chart",
    "description": "Quantity against quantity, with optional bubble sizing for a third variable.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "charts"
  },
  "treemap": {
    "name": "Treemap",
    "description": "A weighted hierarchy as nested areas — where a pie stops working and a bar chart runs out of room.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": null
  },
  "waterfall-chart": {
    "name": "Waterfall Chart",
    "description": "Signed deltas accumulating to a total — the bridge a bar chart and a line chart each tell half of.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "charts"
  },
  "heatmap": {
    "name": "Heatmap",
    "description": "Density across two axes as colour — CSS grid, not a chart library, and the only form here that encodes magnitude without position.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "charts"
  },
  "bullet-chart": {
    "name": "Bullet Chart",
    "description": "An actual against its target and qualitative bands — what `meter`, `gauge` and `progress` cannot say.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "charts"
  },
  "stepper": {
    "name": "Stepper",
    "description": "Progress through a multi-step flow, with per-step state and orientation support.",
    "category": "Navigation",
    "exampleCount": 4,
    "legacy": "stepper"
  },
  "timeline": {
    "name": "Timeline",
    "description": "A vertical sequence of events with completed, active and inactive states.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "timeline"
  },
  "avatar": {
    "name": "Avatar",
    "description": "A user image with a text fallback, and a group with overflow count.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "avatar"
  },
  "pagination": {
    "name": "Pagination",
    "description": "Page links with previous, next and ellipsis.",
    "category": "Navigation",
    "exampleCount": 4,
    "legacy": "pagination"
  },
  "agenda": {
    "name": "Agenda",
    "description": "A chronological list of events grouped by day — the list half of a calendar, and where v2 keeps event display.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "agenda"
  },
  "table": {
    "name": "Table",
    "description": "The static table primitives. For sorting, filtering and pagination use Data Table.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "table"
  },
  "breadcrumb": {
    "name": "Breadcrumb",
    "description": "The trail to the current page, with the last item as plain text.",
    "category": "Navigation",
    "exampleCount": 3,
    "legacy": "breadcrumb"
  },
  "empty": {
    "name": "Empty",
    "description": "The empty-state block: media, title, description and an action.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "empty-state"
  },
  "toolbar": {
    "name": "Toolbar",
    "description": "A Base UI toolbar with arrow-key navigation across grouped buttons, inputs and separators.",
    "category": "Actions",
    "exampleCount": 3,
    "legacy": "toolbar"
  },
  "banner": {
    "name": "Banner",
    "description": "A full-width, tone-coloured message bar over the shared six-tone family — the same tokens button.tsx's `tone` axis reads.",
    "category": "Layout",
    "exampleCount": 3,
    "legacy": "banner"
  },
  "progress": {
    "name": "Progress",
    "description": "Task completion, with optional label and value slots.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "progress"
  },
  "page-header": {
    "name": "Page Header",
    "description": "Breadcrumb, title, description and actions for the top of a page, with an optional flush tab strip.",
    "category": "Layout",
    "exampleCount": 3,
    "legacy": "page-header"
  },
  "description-list": {
    "name": "Description List",
    "description": "Term/detail pairs for record summaries. Renders a real `dl`, so the pairing survives without sight of the layout.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "description-list"
  },
  "kbd": {
    "name": "Kbd",
    "description": "Renders a keyboard key or chord inline, sized to sit in a line of text.",
    "category": "Actions",
    "exampleCount": 3,
    "legacy": "kbd"
  },
  "spinner": {
    "name": "Spinner",
    "description": "An indeterminate loading indicator, sized to the current text.",
    "category": "Data display",
    "exampleCount": 5,
    "legacy": "spinner"
  },
  "icon": {
    "name": "Icon",
    "description": "The built-in glyph set — 34 Phosphor icons, keyed by name, shared by the React binding and the `<ds-icon>` web component.",
    "category": "Utilities",
    "exampleCount": 3,
    "legacy": "icons"
  },
  "button": {
    "name": "Button",
    "description": "The primary action trigger. Eight variants and an eight-colour brand tone axis that compose independently.",
    "category": "Actions",
    "exampleCount": 5,
    "legacy": "buttons"
  },
  "input": {
    "name": "Input",
    "description": "The single-line text field, and the base every other text control borrows its focus ring and invalid styling from.",
    "category": "Forms",
    "exampleCount": 5,
    "legacy": "forms"
  },
  "textarea": {
    "name": "Textarea",
    "description": "A multi-line text field sharing Input's focus and invalid states.",
    "category": "Forms",
    "exampleCount": 4,
    "legacy": "form-controls"
  },
  "field": {
    "name": "Field",
    "description": "The form row primitive — label, control, description and error in one accessible group. Replaces the retired `form` component in this system.",
    "category": "Forms",
    "exampleCount": 5,
    "legacy": "forms"
  },
  "select": {
    "name": "Select",
    "description": "A Base UI listbox for choosing one option from a set, with a rendered trigger and portalled popup.",
    "category": "Forms",
    "exampleCount": 5,
    "legacy": "form-controls"
  },
  "checkbox": {
    "name": "Checkbox",
    "description": "A single boolean control, with indeterminate support via the `parent` prop inside a group.",
    "category": "Forms",
    "exampleCount": 4,
    "legacy": "form-controls"
  },
  "checkbox-group": {
    "name": "Checkbox Group",
    "description": "Manages a set of checkbox values, including the parent select-all relationship.",
    "category": "Forms",
    "exampleCount": 4,
    "legacy": "form-controls"
  },
  "switch": {
    "name": "Switch",
    "description": "An immediate on/off toggle for settings that apply on change.",
    "category": "Forms",
    "exampleCount": 4,
    "legacy": "toggle"
  },
  "slider": {
    "name": "Slider",
    "description": "Selects a number, or a range, by dragging along a track.",
    "category": "Forms",
    "exampleCount": 4,
    "legacy": "form-controls"
  },
  "input-group": {
    "name": "Input Group",
    "description": "Composes addons, icons and buttons around an input inside a single bordered box.",
    "category": "Forms",
    "exampleCount": 4,
    "legacy": "forms"
  },
  "card": {
    "name": "Card",
    "description": "A bordered surface with header, content and footer slots — the default container for grouped content.",
    "category": "Data display",
    "exampleCount": 6,
    "legacy": "card"
  },
  "badge": {
    "name": "Badge",
    "description": "A compact status or category label.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "badges"
  },
  "status": {
    "name": "Status",
    "description": "A dot-and-label state indicator across the shared six-tone family — success, warning, danger, critical, neutral, info.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "status-panel"
  },
  "tag": {
    "name": "Tag",
    "description": "A boxed, tinted label across the shared six-tone family. Absorbs v1's Chip, whose one boolean `warn` axis is now `tone=\"warning\"`.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "tag"
  },
  "panel": {
    "name": "Panel",
    "description": "A sunken section container — the flat sibling of Card, plus a row part for tightly-packed settings lists.",
    "category": "Layout",
    "exampleCount": 3,
    "legacy": "panel"
  },
  "kanban": {
    "name": "Kanban",
    "description": "A board of columns holding cards that move between them by drag or by arrow key.",
    "category": "Data display",
    "exampleCount": 3,
    "legacy": "kanban"
  },
  "skeleton": {
    "name": "Skeleton",
    "description": "A placeholder block for content that has not loaded.",
    "category": "Data display",
    "exampleCount": 4,
    "legacy": "skeleton"
  },
  "sheet": {
    "name": "Sheet",
    "description": "A panel that slides in from an edge — Dialog's modal contract, sized to a column instead of a centred box.",
    "category": "Overlays",
    "exampleCount": 4,
    "legacy": "drawer"
  },
  "drawer": {
    "name": "Drawer",
    "description": "A bottom sheet with drag-to-dismiss and snap points — Sheet's gesture-driven sibling, tuned for touch.",
    "category": "Overlays",
    "exampleCount": 4,
    "legacy": "drawer"
  },
  "tooltip": {
    "name": "Tooltip",
    "description": "A short label on hover or focus. Never put interactive content in one.",
    "category": "Overlays",
    "exampleCount": 3,
    "legacy": "tooltip"
  }
}

export const LEGACY = [
  {
    "slug": "accordion",
    "name": "Accordion"
  },
  {
    "slug": "agenda",
    "name": "Agenda"
  },
  {
    "slug": "alert",
    "name": "Alert"
  },
  {
    "slug": "app-shell",
    "name": "App Shell"
  },
  {
    "slug": "avatar",
    "name": "Avatar"
  },
  {
    "slug": "badges",
    "name": "Badges"
  },
  {
    "slug": "banner",
    "name": "Banner"
  },
  {
    "slug": "breadcrumb",
    "name": "Breadcrumb"
  },
  {
    "slug": "button-extras",
    "name": "Button Extras"
  },
  {
    "slug": "buttons",
    "name": "Buttons"
  },
  {
    "slug": "calendar-view",
    "name": "Calendar View"
  },
  {
    "slug": "callout",
    "name": "Callout"
  },
  {
    "slug": "card",
    "name": "Card"
  },
  {
    "slug": "charts",
    "name": "Charts"
  },
  {
    "slug": "chips",
    "name": "Chips"
  },
  {
    "slug": "code-block",
    "name": "Code Block"
  },
  {
    "slug": "color-picker",
    "name": "Color Picker"
  },
  {
    "slug": "combobox",
    "name": "Combobox"
  },
  {
    "slug": "command-palette",
    "name": "Command Palette"
  },
  {
    "slug": "console-layout",
    "name": "Console Layout"
  },
  {
    "slug": "datagrid",
    "name": "Datagrid"
  },
  {
    "slug": "date-picker",
    "name": "Date Picker"
  },
  {
    "slug": "date-range",
    "name": "Date Range"
  },
  {
    "slug": "date-time",
    "name": "Date Time"
  },
  {
    "slug": "description-list",
    "name": "Description List"
  },
  {
    "slug": "dividers",
    "name": "Dividers"
  },
  {
    "slug": "drawer",
    "name": "Drawer"
  },
  {
    "slug": "email",
    "name": "Email"
  },
  {
    "slug": "empty-state",
    "name": "Empty State"
  },
  {
    "slug": "file-upload",
    "name": "File Upload"
  },
  {
    "slug": "form-controls",
    "name": "Form Controls"
  },
  {
    "slug": "forms",
    "name": "Forms"
  },
  {
    "slug": "icons",
    "name": "Icons"
  },
  {
    "slug": "kanban",
    "name": "Kanban"
  },
  {
    "slug": "kbd",
    "name": "Kbd"
  },
  {
    "slug": "menu",
    "name": "Menu"
  },
  {
    "slug": "metrics",
    "name": "Metrics"
  },
  {
    "slug": "modal",
    "name": "Modal"
  },
  {
    "slug": "multi-select",
    "name": "Multi Select"
  },
  {
    "slug": "number-input",
    "name": "Number Input"
  },
  {
    "slug": "page-header",
    "name": "Page Header"
  },
  {
    "slug": "pagination",
    "name": "Pagination"
  },
  {
    "slug": "panel",
    "name": "Panel"
  },
  {
    "slug": "popover",
    "name": "Popover"
  },
  {
    "slug": "progress",
    "name": "Progress"
  },
  {
    "slug": "rating",
    "name": "Rating"
  },
  {
    "slug": "segmented",
    "name": "Segmented"
  },
  {
    "slug": "skeleton",
    "name": "Skeleton"
  },
  {
    "slug": "sparkline",
    "name": "Sparkline"
  },
  {
    "slug": "spinner",
    "name": "Spinner"
  },
  {
    "slug": "stat-card",
    "name": "Stat Card"
  },
  {
    "slug": "status-panel",
    "name": "Status Panel"
  },
  {
    "slug": "stepper",
    "name": "Stepper"
  },
  {
    "slug": "table",
    "name": "Table"
  },
  {
    "slug": "tabs",
    "name": "Tabs"
  },
  {
    "slug": "tag",
    "name": "Tag"
  },
  {
    "slug": "tag-input",
    "name": "Tag Input"
  },
  {
    "slug": "time-picker",
    "name": "Time Picker"
  },
  {
    "slug": "timeline",
    "name": "Timeline"
  },
  {
    "slug": "toast",
    "name": "Toast"
  },
  {
    "slug": "toggle",
    "name": "Toggle"
  },
  {
    "slug": "toolbar",
    "name": "Toolbar"
  },
  {
    "slug": "tooltip",
    "name": "Tooltip"
  },
  {
    "slug": "tree",
    "name": "Tree"
  },
  {
    "slug": "vertical-nav",
    "name": "Vertical Nav"
  },
  {
    "slug": "web-components",
    "name": "Web Components"
  },
  {
    "slug": "wizard",
    "name": "Wizard"
  }
]
